apiVersion: v1
kind: Secret
metadata:
  name: passthrough-tls-secret
  namespace: demo-testapp-passthrough
type: kubernetes.io/tls
data:
  # Injected automatically by generate-certs.sh
  tls.crt: ""
  tls.key: ""
