# Application TLS Secret for Pass-Through Backend Pod
#
# Can be created via YAML or CLI:
#   oc create secret tls passthrough-tls-secret \
#     --cert=passthrough.crt --key=passthrough.key \
#     -n demo-testapp-passthrough
#
apiVersion: v1
kind: Secret
metadata:
  name: passthrough-tls-secret
  namespace: demo-testapp-passthrough
type: kubernetes.io/tls
data:
  # Base64 encoded certificates:
  # echo -n "$(cat passthrough.crt)" | base64
  tls.crt: ""
  # echo -n "$(cat passthrough.key)" | base64
  tls.key: ""
