apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: passthrough-ingress
  namespace: openshift-ingress-operator
spec:
  domain: passthrough.apps.okd-sno.brainybots.cloud
  replicas: 1
  endpointPublishingStrategy:
    type: HostNetwork
  # Sharding: Only route traffic for namespaces with this label
  namespaceSelector:
    matchLabels:
      ingress.traffic.type: passthrough
  # Sharding: Only route traffic for routes with this label
  routeSelector:
    matchLabels:
      type: passthrough
