apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: testapp-passthrough-ingress
  namespace: openshift-ingress-operator
spec:
  domain: testapp-passthrough.apps.okd-sno.brainybots.cloud
  replicas: 1
  endpointPublishingStrategy:
    type: HostNetwork
  # Enterprise Sharding: Dedicate this ingress controller to namespaces labeled ingress=testapp-passthrough
  namespaceSelector:
    matchLabels:
      ingress: testapp-passthrough
