apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: passthrough-app-route
  namespace: demo-testapp-passthrough
  labels:
    app: passthrough-app
spec:
  host: passthrough-app.testapp-passthrough.apps.okd-sno.brainybots.cloud
  to:
    kind: Service
    name: passthrough-app-svc
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
