apiVersion: v1
kind: Secret
metadata:
  name: custom-wildcard-tls
  namespace: openshift-ingress
type: kubernetes.io/tls
data:
  # Base64 encoded certificates:
  # echo -n "$(cat server.crt)" | base64
  tls.crt: ""
  # echo -n "$(cat server.key)" | base64
  tls.key: ""
