apiVersion: v1
kind: Secret
metadata:
  name: custom-wildcard-tls
  namespace: openshift-ingress
type: kubernetes.io/tls
data:
  # Paste base64 strings here:
  # On macOS/Linux run:
  #   cat server.crt | base64 | tr -d '\n'
  #   cat server.key | base64 | tr -d '\n'
  tls.crt: ""
  tls.key: ""
