apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: testapp-edge-ingress
  namespace: openshift-ingress-operator
spec:
  domain: testapp-edge.apps.okd-sno.brainybots.cloud
  replicas: 1
  endpointPublishingStrategy:
    type: HostNetwork
  defaultCertificate:
    name: custom-wildcard-tls
  # Enterprise Sharding: Dedicate this ingress controller to namespaces labeled ingress=testapp-edge
  namespaceSelector:
    matchLabels:
      ingress: testapp-edge
