apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: edge-ingress
  namespace: openshift-ingress-operator
spec:
  domain: edge.apps.okd-sno.brainybots.cloud
  replicas: 1
  endpointPublishingStrategy:
    type: HostNetwork
  defaultCertificate:
    name: custom-wildcard-tls
  # Sharding: Only route traffic for namespaces with this label
  namespaceSelector:
    matchLabels:
      ingress.traffic.type: edge
  # Sharding: Only route traffic for routes with this label
  routeSelector:
    matchLabels:
      type: edge
