apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: edge-app-ingress
  namespace: openshift-ingress-operator
spec:
  replicas: 1
  domain: edge-app.apps.okd-sno.brainybots.cloud
  defaultCertificate:
    name: custom-wildcard-tls
  namespaceSelector:
    matchLabels:
      ingress: edge-app
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
